swagger: "2.0"
info:
  description: "REST API for ARTICLES with basic functionality."
  version: "1.0.0"
  title: "ARTICLES REST API"
  contact:
    email: ".....@gmail.com"
tags:
  - name: "connections"
    description: "Access to database connections"
schemes:
  - "http"
paths:
  /articles/:
      get:
        tags:
          - "articles"
        summary: "List articles"
        description: "Returns list of articles"
        operationId: "articles"
        produces:
          - "application/json"
        responses:
          200:
            description: "OK"
            schema:
              type: "array"
              items:
              $ref: "#/definitions/Article"
      post:
        tags:
          - "article"
        summary: "Add a new article to the list of connections"
        description: ""
        operationId: "postArticle"
        produces:
          - "application/json"
        parameters:
          - in: "body"
            name: "body"
            description: "Article object that needs to be added to the list of articles"
            required: true
            schema:
              $ref: "#/definitions/Article"
        responses:
          201:
            description: "Created"
            schema:
               $ref: "#/definitions/GeneralResponse"
  /articles/{articleID}:
            required: true
            type: "integer"
            format: "int64"
          - in: "body"
            name: "body"
            description: "Article object that needs to be updated in the list of articles"
            required: true
            schema:
              $ref: "#/definitions/Article"
        responses:
          200:
            description: "OK"
          404:
            description: "Could not update the entity: The specified entity does not exist!"
      delete:
        tags:
          - "article"
        summary: "Deletes a article by ID"
        description: ""
        operationId: "deleteArticle"
        parameters:
          - name: "articleID"
            in: "path"
            description: "Article ID to delete"
            required: true
            type: "integer"
            format: "int64"
        responses:
          200:
            description: "All corresponding entities were deleted."
          400:
            description: "Could not delete entities: Something went wrong!"
definitions:
  Article:
    type: "object"
    properties:
      title:
        type: "string"
        description: "Article title"
      content:
        type: "string"
        description: "Article content"
  ArticleEntity:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "Article ID"
      category:
        $ref: "#/definitions/Article"
        description: "Article content"
  GeneralResponse:
    type: "object"
    properties:
      message:
        type: "string"
        description: "response message"