swagger: "2.0"
info:
  description: "REST API for MySQL with basic functionality."
  version: "1.0.0"
  title: "MySQL REST API"
  contact:
    email: "shah.huseyinli@gmail.com"
tags:
- name: "connections"
  description: "Access to database connections"
schemes:
- "http"
paths:
  /connections:
    get:
      tags:
      - "connections"
      summary: "List connections"
      description: "Returns list of connections"
      operationId: "getConnection"
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ConnectionEntity"
    post:
      tags:
      - "connection"
      summary: "Add a new connection to the list of connections"
      description: ""
      operationId: "addConnection"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Connection object that needs to be added to the list of connections"
        required: true
        schema:
          $ref: "#/definitions/Connection"
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/ConnectionEntity"
  /connections/{connectionId}:
    get:
      tags:
      - "connection"
      summary: "Find connection by ID"
      description: "Returns a single connection"
      operationId: "getConnectionById"
      produces:
      - "application/json"
      parameters:
      - name: "connectionId"
        in: "path"
        description: "ID of connection to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/ConnectionEntity" 
    put:
      tags:
      - "connection"
      summary: "Update an existing connection by ID"
      description: ""
      operationId: "updateConnectionById"
      produces:
      - "application/json"
      parameters:
      - name: "connectionId"
        in: "path"
        description: "ID of connection to update"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Connection object that needs to be updated in the list of connections"
        required: true
        schema:
          $ref: "#/definitions/Connection"
      responses:
        200:
          description: "OK"
        404:
          description: "Could not update the entity: The specified entity does not exist!"
    delete:
      tags:
      - "connection"
      summary: "Deletes a connection by ID"
      description: ""
      operationId: "deleteConnectionById"
      parameters:
      - name: "connectionId"
        in: "path"
        description: "Connection ID to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "All corresponding entities were deleted."
        400:
          description: "Could not delete entities: Something went wrong!"
definitions:
  Connection:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Custom name of the database instance"
      hostName:
        type: "string"
        description: "Hostname of the database"
      port:
        type: "integer"
        format: "int32"
        description: "Port where the database runs"
      databaseName:
        type: "string"
        description: "Name of the database"
      username:
        type: "string"
        description: "Username to connect to the database"
      password:
        type: "string"
        description: "Password to connect to the database"
  ConnectionEntity:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "Connection entity ID"
      category:
        $ref: "#/definitions/Connection" 
    